package projecteuler;

public class Question12 {

	/*	The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
		1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
		Let us list the factors of the first seven triangle numbers:
		1: 1
		3: 1,3
		6: 1,2,3,6
		10: 1,2,5,10
		15: 1,3,5,15
		21: 1,3,7,21
		28: 1,2,4,7,14,28
		We can see that 28 is the first triangle number to have over five divisors.
		What is the value of the first triangle number to have over five hundred divisors?
	*/
	
	public static long diviserCount (long number){
		
		long[] divideList = new long[5013];
		long limit = (int)Math.sqrt(number);
		long counter = 0;
		long i=0;
		
		
		for(i=1;i<=limit;i++) {
			if(number%i == 0 ) {
				divideList[(int) counter]=i;
				counter++;
				divideList[(int) counter]=number/i;
				counter++;
				
			}
		}
		
		return counter+1;
		
	}
	public static void main (String args[]) {
		
		long i=0;
		long number = 0;
		
		while(diviserCount(number)<=500) {
			
			i++;
			number = number +i;
			
		}
		
		System.out.println("500 den fazla böleni olan sayý:" + number);
		
		
		
	}
}
