package projecteuler;

public class Question2 {

	/*
	 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	*/
	
	public static void main(String args[]) {
		
		int ilk=1, ikinci=1, yedek=0, toplam=0;
				
		while(ikinci<4000000) {
			yedek=ilk+ikinci;
			if(yedek>4000000) {
				break;
			}
			ilk=ikinci;
			ikinci=yedek;
			
			if(ikinci%2==0) {
				toplam=toplam+ikinci;
				System.out.print("\n" + ikinci + "\n");
			}
			System.out.print(ikinci + "\n");
		}
		System.err.print(toplam);
	}
}
